name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - name: Checkout MiniVM
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Checkout Test Scripts
      uses: actions/checkout@v2
      with:
        repository: pku-minic/MiniVM-test
        path: test
        submodules: false

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMINIVM_LEGACY_MODE=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: $GITHUB_WORKSPACE/test/run_test.sh ./minivm
